name: MSBuild

on: [push, pull_request]

permissions:
  contents: read

jobs:
  msbuild:
    runs-on: windows-latest
    permissions: write-all
    
    strategy:
      matrix:
        configuration: [Release]
        platform: [x64]

    steps:
    - uses: actions/checkout@v4.2.2

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Build
      working-directory: ${{ env.GITHUB_WORKSPACE }}
      run: msbuild Arsenal.sln /p:Platform=${{ matrix.platform }} /p:Configuration=${{ matrix.configuration }}
    
    - uses: actions/upload-artifact@v4.6.2
      with:
        name: Arsenal${{ matrix.platform }}${{ matrix.configuration }}
        path: output/${{ matrix.platform }}/${{ matrix.configuration }}/*.dll

    - uses: dev-drprasad/delete-older-releases@v0.3.4
      with:
        keep_latest: 0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Create release
      uses: actions/create-release@v1.1.4
      id: create_release
      with:
        draft: false
        prerelease: false
        release_name: Arsenal
        tag_name: v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Upload release
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: output/${{ matrix.platform }}/${{ matrix.configuration }}/Arsenal${{ matrix.platform }}${{ matrix.configuration }}.dll
        asset_name: Arsenal${{ matrix.platform }}${{ matrix.configuration }}.dll
        asset_content_type: application/dll